# Generated by Django 3.0.8 on 2020-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photoUrl', models.URLField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
            ],
        ),
    ]
