# Generated by Django 3.0.8 on 2021-01-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
