# Generated by Django 3.0.8 on 2021-01-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='myapi.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCount', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderedProducts',
            field=models.ManyToManyField(blank=True, through='myapi.ProductsInOrder', to='myapi.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='myapi.Restaurant'),
        ),
    ]
