# Generated by Django 3.0.8 on 2021-01-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20210118_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
