# Generated by Django 3.0.8 on 2021-01-23 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210118_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issueDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='plannedDay',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='plannedTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='issueTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
