# Generated by Django 3.0.8 on 2021-01-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20210123_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='plannedTime',
            new_name='plannedDate',
        ),
    ]
