# Generated by Django 3.0.8 on 2021-01-23 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20210123_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plannedDay',
        ),
        migrations.AddField(
            model_name='order',
            name='plannedTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='plannedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
