# Generated by Django 3.0.8 on 2021-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20210131_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_restaurant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
