# Generated by Django 3.0.8 on 2021-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_auto_20210201_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
