# Generated by Django 3.0.8 on 2021-01-31 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20210201_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to='myapi.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_restaurant',
        ),
    ]
