# Generated by Django 3.0.8 on 2021-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_auto_20210201_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_work',
            field=models.IntegerField(default=5),
        ),
    ]
