# Generated by Django 3.0.8 on 2021-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_auto_20210201_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active_work',
            field=models.IntegerField(default=0),
        ),
    ]
