# Generated by Django 3.0.8 on 2021-02-02 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_restaurant_active_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='begin_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
    ]
