# Generated by Django 3.0.8 on 2021-02-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_auto_20210202_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
